name: docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [ linux ]
    environment: Docker Hub
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: x86_64-unknown-linux-musl-bin
      - run: |
          chmod a+x aliyundrive-fuse
          mv aliyundrive-fuse aliyundrive-fuse-amd64
      - uses: actions/download-artifact@v2
        with:
          name: i686-unknown-linux-musl-bin
      - run: |
          chmod a+x aliyundrive-fuse
          mv aliyundrive-fuse aliyundrive-fuse-386
      - uses: actions/download-artifact@v2
        with:
          name: aarch64-unknown-linux-musl-bin
      - run: |
          chmod a+x aliyundrive-fuse
          mv aliyundrive-fuse aliyundrive-fuse-arm64
      - uses: actions/download-artifact@v2
        with:
          name: armv7-unknown-linux-musleabihf-bin
      - run: |
          chmod a+x aliyundrive-fuse
          mv aliyundrive-fuse aliyundrive-fuse-armv7
      - uses: actions/download-artifact@v2
        with:
          name: arm-unknown-linux-musleabihf-bin
      - run: |
          chmod a+x aliyundrive-fuse
          mv aliyundrive-fuse aliyundrive-fuse-armv6
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            messense/aliyundrive-fuse
            ghcr.io/messense/aliyundrive-fuse
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Setup QEMU
        uses: dbhi/qus/action@main
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Docker Hub Description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: messense/aliyundrive-fuse

